### PR TITLE
Refactored module to support TcpSockets

### PR DESCRIPTION
**Pull request by IsaaX**
Steps taken for the refactor:
1. BluetoothDeviceSocketConnection -> BluetoothSocketConnection
2. Established a ISocketConnection interface
3. renamed printer -> PosPrinter to distinguish the type of printer (adds clarity against regular printers which is potential in my application)
4. Moved the `BluetoothDeviceSocketConnection.outputStream` to the `PosPrinter` class and have any commands needed to be done at that level. This is how I managed to consolidate the logic between TCP and Bluetooth since they both use `OutputStream`
5. All the commands related to `BluetoothDeviceSocketConnection.outputStream` has been moved to PosPrinter 

`this.bluetoothPrinter.newLine()` now becomes `this.newLine()` or `posPrinter.newLine()` which makes it connection agnostic. This allows for further types of connection as long as it implements the `ISocketConnection`. 

Things that I did when refactoring is to keep the API intact as much as possible. so now everything can be managed with the `PosPrinter posPrinterInstance`. This is a pretty big change but think it keeps certain pieces of code isolated from one another so you can continue to expand on the bluetooth portions of it and I can continue on the Tcp aspect of the code base. 

I haven't updated the documentation yet, wanted to get your input before committing to it 

here's the example code you asked for with this code which I successfully printed on a `Epson tm-t20ii` 
looks almost identical to your example 

```
TcpSocketConnection printer = new TcpSocketConnection("192.111.100.11", 9100);
        this.posPrinter = new PosPrinter(printer, 203, 48f, 32);

        posPrinter
                .printFormattedText(
                                "[C]<u><font size='big'>ORDER N°045</font></u>\n" +
                                "[L]\n" +
                                "[C]================================\n" +
                                "[L]\n" +
                                "[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
                                "[L]  + Size : S\n" +
                                "[L]\n" +
                                "[L]<b>AWESOME HAT</b>[R]24.99e\n" +
                                "[L]  + Size : 57/58\n" +
                                "[L]\n" +
                                "[C]--------------------------------\n" +
                                "[L][R]TOTAL PRICE :[R]34.98e\n" +
                                "[L][R]TAX :[R]4.23e\n" +
                                "[L]\n" +
                                "[C]================================\n" +
                                "[L]\n" +
                                "[L]<font size='tall'>Customer :</font>\n" +
                                "[L]Raymond DUPONT\n" +
                                "[L]5 rue des girafes\n" +
                                "[L]31547 PERPETES\n" +
                                "[L]Tel : +33801201456\n" +
                                "[L]\n" +
                                "[C]<barcode type='ean13' height='10'>831254784551</barcode>\n" +
                                "[C]<qrcode size='20'>http://www.developpeur-web.dantsu.com/</qrcode>"
                );
```
 

Hope this is helpful. Let me know what your thoughts are and see if we can reach an agreement.

### CODE REVIEW

**Comment by DantSu** [comment]
Thanks for all this works.
I reviewed your code and you do this in the right way. 

I cannot accept your pull request because the package name is `printerthermal_escpos_bluetooth` BUT I will create a new repo named  `DantSu/ThermalPrinter-ESCPOS-Android` with a package named `thermalprinter_escpos`. I will do the upgrade based on your PR. I will contact you when everything is finished because I would like you to add your name in the project contributors.

**Comment by IsaaX** [comment]
Excellent, let me know if I can help. This is my full time job so I'm able to have dedicated time to be able to help code and add to this library. I'll have more things in mind (like opening cash registers) to add and will run things by you before making changes in order to keep ourselves in sync. 

 The idea is eventually i'm going to create a `react-native` module that will reference this library internally and be opened source as well.

**Comment by DantSu** [comment]
Initially, the main reason I created this project was to implement it in `react-native`. But I never had the time and the skills to develop the same thing in Swift. The goal was to be able to start an activity with only one string to print a complete sales receipt. :)

**Comment by DantSu** [comment]
Hi !

https://github.com/DantSu/ESCPOS-ThermalPrinter-Android

Here is the new repository. Can you git clone the project, for testing TCP ?
Add your name and website in the bottom of README file. (I have created a line `Name - TCP Protocol`. Change it to what you want ;) )

**Pull request closed without merging**
