### PR TITLE
Sanxy patch 1

### PR DESCRIPTION
**Pull request by sanxy**

### CODE REVIEW

**Comment by DantSu** [comment]
Hi, thx for your contribution.

**Comment by DantSu** [comment]
I just created a new release `1.1.0`. it adds the QR code tag. My thermal printer does not seem to support these commands. Can you test with yours?
`<qrcode size='3'>http://www.developpeur-web.dantsu.com/</qrcode>`

**Comment by steamerstudio** [comment]
It fails for me whereas my printer is compatible with QR codes. Nothing is printed.
Btw, the EAN13 barcode feature prints the "bars" actually, but not the figures as shown on the picture (cf readme)

**Comment by DantSu** [comment]
To be sure, have you changed the dependency version to `1.1.0`?

```
dependencies {
    ...
    implementation 'com.github.DantSu:PrinterThermal-ESCPOS-Android:1.1.0'
}
```

**Comment by steamerstudio** [comment]
I downloaded directly this repo and ran "MainActivity" on my smartphone
Indeed, for some reason, I'm getting the following error when I use dependency in a separate project:
ERROR: Failed to resolve: com.github.DantSu:PrinterThermal-ESCPOS-Android:1.1.0

**Comment by DantSu** [comment]
Ok thx for your feedback.

For the error, have you follow the first step ?

> Step 1. Add the JitPack repository to your build file. Add it in your root /build.gradle at the end of repositories:
> 
> ```
> allprojects {
>     repositories {
>         ...
>         maven { url 'https://jitpack.io' }
>     }
> }
> ```

**Comment by steamerstudio** [comment]
my bad my bad... I just fixed with that. Thanks

**Comment by steamerstudio** [comment]
Well, now it does not recognize the QR Code tag and print "<qrcode size='3'>http://www.developpeur-web.dantsu.com/</qrcode>"

**Comment by DantSu** [comment]
I must have forgotten something. I don't know what yet, but I'll find it. ^^

**Comment by DantSu** [comment]
QR code working for all printer thermal devices now :)

**Pull request merged**
